In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sb
from matplotlib import rcParams
import math
import statsmodels.api as sm
import mglearn
from sklearn.model_selection import train_test_split

#### New merged data set
df = pd.read_csv('/home/damien/Desktop/Data_Group_Project/SN_m_tot_V2.0EDIT.csv')
df2 = pd.read_csv('/home/damien/Desktop/Data_Group_Project/Birr Castle telegraphic reporting station_1921-1956.csv')

merged_data = df.merge(df2, left_on=['year','month'], right_on=['Year','Month'])
merged_data

,year,month,sunspot average,Year,Month,Daily,Max at 9h (F),Min at 9h (F),Max at 21h (F),Min at 21h (F),Max at 9h (C),Min at 9h (C),Max at 21h (C),Min at 21h (C),Date
0,1921,1,52.5,1921,1,1,53.0,43.0,NaN,NaN,11.7,6.1,NaN,NaN,01/01/1921
1,1921,1,52.5,1921,1,2,49.0,47.0,NaN,NaN,9.4,8.3,NaN,NaN,02/01/1921
2,1921,1,52.5,1921,1,3,55.0,40.0,NaN,NaN,12.8,4.4,NaN,NaN,03/01/1921
3,1921,1,52.5,1921,1,4,53.0,40.0,NaN,NaN,11.7,4.4,NaN,NaN,04/01/1921
4,1921,1,52.5,1921,1,5,52.0,35.0,NaN,NaN,11.1,1.7,NaN,NaN,05/01/1921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12413,1954,12,11.3,1954,12,27,NaN,44.0,52.0,NaN,NaN,6.7,11.1,NaN,27/12/1954
12414,1954,12,11.3,1954,12,28,NaN,48.0,52.0,NaN,NaN,8.9,11.1,NaN,28/12/1954
12415,1954,12,11.3,1954,12,29,NaN,46.0,50.0,NaN,NaN,7.8,10.0,NaN,29/12/1954
12416,1954,12,11.3,1954,12,30,NaN,43.0,48.0,NaN,NaN,6.1,8.9,NaN,30/12/1954
12417,1954,12,11.3,1954,12,31,NaN,46.0,49.0,NaN,NaN,7.8,9.4,NaN,31/12/1954

In [2]:
print('Shape of features: ', merged_data.shape)

Shape of features:  (12418, 15)

In [3]:
merged_data = pd.get_dummies(merged_data)

In [4]:
merged_data = merged_data.fillna(0)

In [5]:
# label for value we want to predict
labels = np.array(merged_data['Min at 9h (F)'])
labels = np.array(merged_data['Max at 9h (F)'])

# remove label column, axis1 refers to column
merged_data = merged_data.drop('Min at 9h (F)', axis = 1)
merged_data = merged_data.drop('Max at 9h (F)', axis = 1)

feature_list = list(merged_data.columns)

merged_data = np.array(merged_data)

In [6]:
# using Skicit-learn to split the data into training and testing sets
# splitting into testing and training sets

train_merged_data, test_merged_data, train_labels, test_labels = train_test_split(merged_data, labels, test_size = 0.25, random_state = 42)

In [7]:
print('Training merged_data Shape: ', train_merged_data.shape)
print('Training labels Shape: ', train_merged_data.shape)
print('Testing merged_data Shape: ', train_merged_data.shape)
print('Testing labels Shape: ', train_merged_data.shape)

Training merged_data Shape:  (9313, 12430)
Training labels Shape:  (9313, 12430)
Testing merged_data Shape:  (9313, 12430)
Testing labels Shape:  (9313, 12430)

In [8]:
feature_list

['year',
 'month',
 'sunspot average',
 'Year',
 'Month',
 'Daily',
 'Max at 21h (F)',
 'Min at 21h (F)',
 'Max at 9h (C)',
 'Min at 9h (C)',
 'Max at 21h (C)',
 'Min at 21h (C)',
 'Date_01/01/1921',
 'Date_01/01/1922',
 'Date_01/01/1923',
 'Date_01/01/1924',
 'Date_01/01/1925',
 'Date_01/01/1926',
 'Date_01/01/1927',
 'Date_01/01/1928',
 'Date_01/01/1929',
 'Date_01/01/1930',
 'Date_01/01/1931',
 'Date_01/01/1932',
 'Date_01/01/1933',
 'Date_01/01/1934',
 'Date_01/01/1935',
 'Date_01/01/1936',
 'Date_01/01/1937',
 'Date_01/01/1938',
 'Date_01/01/1939',
 'Date_01/01/1940',
 'Date_01/01/1941',
 'Date_01/01/1942',
 'Date_01/01/1943',
 'Date_01/01/1944',
 'Date_01/01/1945',
 'Date_01/01/1946',
 'Date_01/01/1947',
 'Date_01/01/1948',
 'Date_01/01/1949',
 'Date_01/01/1950',
 'Date_01/01/1951',
 'Date_01/01/1952',
 'Date_01/01/1953',
 'Date_01/01/1954',
 'Date_01/02/1921',
 'Date_01/02/1922',
 'Date_01/02/1923',
 'Date_01/02/1924',
 'Date_01/02/1925',
 'Date_01/02/1926',
 'Date_01/02/1927',
 'Date_01/02/1928',
 'Date_01/02/1929',
 'Date_01/02/1930',
 'Date_01/02/1931',
 'Date_01/02/1932',
 'Date_01/02/1933',
 'Date_01/02/1934',
 'Date_01/02/1935',
 'Date_01/02/1936',
 'Date_01/02/1937',
 'Date_01/02/1938',
 'Date_01/02/1939',
 'Date_01/02/1940',
 'Date_01/02/1941',
 'Date_01/02/1942',
 'Date_01/02/1943',
 'Date_01/02/1944',
 'Date_01/02/1945',
 'Date_01/02/1946',
 'Date_01/02/1947',
 'Date_01/02/1948',
 'Date_01/02/1949',
 'Date_01/02/1950',
 'Date_01/02/1951',
 'Date_01/02/1952',
 'Date_01/02/1953',
 'Date_01/02/1954',
 'Date_01/03/1921',
 'Date_01/03/1922',
 'Date_01/03/1923',
 'Date_01/03/1924',
 'Date_01/03/1925',
 'Date_01/03/1926',
 'Date_01/03/1927',
 'Date_01/03/1928',
 'Date_01/03/1929',
 'Date_01/03/1930',
 'Date_01/03/1931',
 'Date_01/03/1932',
 'Date_01/03/1933',
 'Date_01/03/1934',
 'Date_01/03/1935',
 'Date_01/03/1936',
 'Date_01/03/1937',
 'Date_01/03/1938',
 'Date_01/03/1939',
 'Date_01/03/1940',
 'Date_01/03/1941',
 'Date_01/03/1942',
 'Date_01/03/1943',
 'Date_01/03/1944',
 'Date_01/03/1945',
 'Date_01/03/1946',
 'Date_01/03/1947',
 'Date_01/03/1948',
 'Date_01/03/1949',
 'Date_01/03/1950',
 'Date_01/03/1951',
 'Date_01/03/1952',
 'Date_01/03/1953',
 'Date_01/03/1954',
 'Date_01/04/1921',
 'Date_01/04/1922',
 'Date_01/04/1923',
 'Date_01/04/1924',
 'Date_01/04/1925',
 'Date_01/04/1926',
 'Date_01/04/1927',
 'Date_01/04/1928',
 'Date_01/04/1929',
 'Date_01/04/1930',
 'Date_01/04/1931',
 'Date_01/04/1932',
 'Date_01/04/1933',
 'Date_01/04/1934',
 'Date_01/04/1935',
 'Date_01/04/1936',
 'Date_01/04/1937',
 'Date_01/04/1938',
 'Date_01/04/1939',
 'Date_01/04/1940',
 'Date_01/04/1941',
 'Date_01/04/1942',
 'Date_01/04/1943',
 'Date_01/04/1944',
 'Date_01/04/1945',
 'Date_01/04/1946',
 'Date_01/04/1947',
 'Date_01/04/1948',
 'Date_01/04/1949',
 'Date_01/04/1950',
 'Date_01/04/1951',
 'Date_01/04/1952',
 'Date_01/04/1953',
 'Date_01/04/1954',
 'Date_01/05/1921',
 'Date_01/05/1922',
 'Date_01/05/1923',
 'Date_01/05/1924',
 'Date_01/05/1925',
 'Date_01/05/1926',
 'Date_01/05/1927',
 'Date_01/05/1928',
 'Date_01/05/1929',
 'Date_01/05/1930',
 'Date_01/05/1931',
 'Date_01/05/1932',
 'Date_01/05/1933',
 'Date_01/05/1934',
 'Date_01/05/1935',
 'Date_01/05/1936',
 'Date_01/05/1937',
 'Date_01/05/1938',
 'Date_01/05/1939',
 'Date_01/05/1940',
 'Date_01/05/1941',
 'Date_01/05/1942',
 'Date_01/05/1943',
 'Date_01/05/1944',
 'Date_01/05/1945',
 'Date_01/05/1946',
 'Date_01/05/1947',
 'Date_01/05/1948',
 'Date_01/05/1949',
 'Date_01/05/1950',
 'Date_01/05/1951',
 'Date_01/05/1952',
 'Date_01/05/1953',
 'Date_01/05/1954',
 'Date_01/06/1921',
 'Date_01/06/1922',
 'Date_01/06/1923',
 'Date_01/06/1924',
 'Date_01/06/1925',
 'Date_01/06/1926',
 'Date_01/06/1927',
 'Date_01/06/1928',
 'Date_01/06/1929',
 'Date_01/06/1930',
 'Date_01/06/1931',
 'Date_01/06/1932',
 'Date_01/06/1933',
 'Date_01/06/1934',
 'Date_01/06/1935',
 'Date_01/06/1936',
 'Date_01/06/1937',
 'Date_01/06/1938',
 'Date_01/06/1939',
 'Date_01/06/1940',
 'Date_01/06/1941',
 'Date_01/06/1942',
 'Date_01/06/1943',
 'Date_01/06/1944',
 'Date_01/06/1945',
 'Date_01/06/1946',
 'Date_01/06/1947',
 'Date_01/06/1948',
 'Date_01/06/1949',
 'Date_01/06/1950',
 'Date_01/06/1951',
 'Date_01/06/1952',
 'Date_01/06/1953',
 'Date_01/06/1954',
 'Date_01/07/1921',
 'Date_01/07/1922',
 'Date_01/07/1923',
 'Date_01/07/1924',
 'Date_01/07/1925',
 'Date_01/07/1926',
 'Date_01/07/1927',
 'Date_01/07/1928',
 'Date_01/07/1929',
 'Date_01/07/1930',
 'Date_01/07/1931',
 'Date_01/07/1932',
 'Date_01/07/1933',
 'Date_01/07/1934',
 'Date_01/07/1935',
 'Date_01/07/1936',
 'Date_01/07/1937',
 'Date_01/07/1938',
 'Date_01/07/1939',
 'Date_01/07/1940',
 'Date_01/07/1941',
 'Date_01/07/1942',
 'Date_01/07/1943',
 'Date_01/07/1944',
 'Date_01/07/1945',
 'Date_01/07/1946',
 'Date_01/07/1947',
 'Date_01/07/1948',
 'Date_01/07/1949',
 'Date_01/07/1950',
 'Date_01/07/1951',
 'Date_01/07/1952',
 'Date_01/07/1953',
 'Date_01/07/1954',
 'Date_01/08/1921',
 'Date_01/08/1922',
 'Date_01/08/1923',
 'Date_01/08/1924',
 'Date_01/08/1925',
 'Date_01/08/1926',
 'Date_01/08/1927',
 'Date_01/08/1928',
 'Date_01/08/1929',
 'Date_01/08/1930',
 'Date_01/08/1931',
 'Date_01/08/1932',
 'Date_01/08/1933',
 'Date_01/08/1934',
 'Date_01/08/1935',
 'Date_01/08/1936',
 'Date_01/08/1937',
 'Date_01/08/1938',
 'Date_01/08/1939',
 'Date_01/08/1940',
 'Date_01/08/1941',
 'Date_01/08/1942',
 'Date_01/08/1943',
 'Date_01/08/1944',
 'Date_01/08/1945',
 'Date_01/08/1946',
 'Date_01/08/1947',
 'Date_01/08/1948',
 'Date_01/08/1949',
 'Date_01/08/1950',
 'Date_01/08/1951',
 'Date_01/08/1952',
 'Date_01/08/1953',
 'Date_01/08/1954',
 'Date_01/09/1921',
 'Date_01/09/1922',
 'Date_01/09/1923',
 'Date_01/09/1924',
 'Date_01/09/1925',
 'Date_01/09/1926',
 'Date_01/09/1927',
 'Date_01/09/1928',
 'Date_01/09/1929',
 'Date_01/09/1930',
 'Date_01/09/1931',
 'Date_01/09/1932',
 'Date_01/09/1933',
 'Date_01/09/1934',
 'Date_01/09/1935',
 'Date_01/09/1936',
 'Date_01/09/1937',
 'Date_01/09/1938',
 'Date_01/09/1939',
 'Date_01/09/1940',
 'Date_01/09/1941',
 'Date_01/09/1942',
 'Date_01/09/1943',
 'Date_01/09/1944',
 'Date_01/09/1945',
 'Date_01/09/1946',
 'Date_01/09/1947',
 'Date_01/09/1948',
 'Date_01/09/1949',
 'Date_01/09/1950',
 'Date_01/09/1951',
 'Date_01/09/1952',
 'Date_01/09/1953',
 'Date_01/09/1954',
 'Date_01/10/1921',
 'Date_01/10/1922',
 'Date_01/10/1923',
 'Date_01/10/1924',
 'Date_01/10/1925',
 'Date_01/10/1926',
 'Date_01/10/1927',
 'Date_01/10/1928',
 'Date_01/10/1929',
 'Date_01/10/1930',
 'Date_01/10/1931',
 'Date_01/10/1932',
 'Date_01/10/1933',
 'Date_01/10/1934',
 'Date_01/10/1935',
 'Date_01/10/1936',
 'Date_01/10/1937',
 'Date_01/10/1938',
 'Date_01/10/1939',
 'Date_01/10/1940',
 'Date_01/10/1941',
 'Date_01/10/1942',
 'Date_01/10/1943',
 'Date_01/10/1944',
 'Date_01/10/1945',
 'Date_01/10/1946',
 'Date_01/10/1947',
 'Date_01/10/1948',
 'Date_01/10/1949',
 'Date_01/10/1950',
 'Date_01/10/1951',
 'Date_01/10/1952',
 'Date_01/10/1953',
 'Date_01/10/1954',
 'Date_01/11/1921',
 'Date_01/11/1922',
 'Date_01/11/1923',
 'Date_01/11/1924',
 'Date_01/11/1925',
 'Date_01/11/1926',
 'Date_01/11/1927',
 'Date_01/11/1928',
 'Date_01/11/1929',
 'Date_01/11/1930',
 'Date_01/11/1931',
 'Date_01/11/1932',
 'Date_01/11/1933',
 'Date_01/11/1934',
 'Date_01/11/1935',
 'Date_01/11/1936',
 'Date_01/11/1937',
 'Date_01/11/1938',
 'Date_01/11/1939',
 'Date_01/11/1940',
 'Date_01/11/1941',
 'Date_01/11/1942',
 'Date_01/11/1943',
 'Date_01/11/1944',
 'Date_01/11/1945',
 'Date_01/11/1946',
 'Date_01/11/1947',
 'Date_01/11/1948',
 'Date_01/11/1949',
 'Date_01/11/1950',
 'Date_01/11/1951',
 'Date_01/11/1952',
 'Date_01/11/1953',
 'Date_01/11/1954',
 'Date_01/12/1921',
 'Date_01/12/1922',
 'Date_01/12/1923',
 'Date_01/12/1924',
 'Date_01/12/1925',
 'Date_01/12/1926',
 'Date_01/12/1927',
 'Date_01/12/1928',
 'Date_01/12/1929',
 'Date_01/12/1930',
 'Date_01/12/1931',
 'Date_01/12/1932',
 'Date_01/12/1933',
 'Date_01/12/1934',
 'Date_01/12/1935',
 'Date_01/12/1936',
 'Date_01/12/1937',
 'Date_01/12/1938',
 'Date_01/12/1939',
 'Date_01/12/1940',
 'Date_01/12/1941',
 'Date_01/12/1942',
 'Date_01/12/1943',
 'Date_01/12/1944',
 'Date_01/12/1945',
 'Date_01/12/1946',
 'Date_01/12/1947',
 'Date_01/12/1948',
 'Date_01/12/1949',
 'Date_01/12/1950',
 'Date_01/12/1951',
 'Date_01/12/1952',
 'Date_01/12/1953',
 'Date_01/12/1954',
 'Date_02/01/1921',
 'Date_02/01/1922',
 'Date_02/01/1923',
 'Date_02/01/1924',
 'Date_02/01/1925',
 'Date_02/01/1926',
 'Date_02/01/1927',
 'Date_02/01/1928',
 'Date_02/01/1929',
 'Date_02/01/1930',
 'Date_02/01/1931',
 'Date_02/01/1932',
 'Date_02/01/1933',
 'Date_02/01/1934',
 'Date_02/01/1935',
 'Date_02/01/1936',
 'Date_02/01/1937',
 'Date_02/01/1938',
 'Date_02/01/1939',
 'Date_02/01/1940',
 'Date_02/01/1941',
 'Date_02/01/1942',
 'Date_02/01/1943',
 'Date_02/01/1944',
 'Date_02/01/1945',
 'Date_02/01/1946',
 'Date_02/01/1947',
 'Date_02/01/1948',
 'Date_02/01/1949',
 'Date_02/01/1950',
 'Date_02/01/1951',
 'Date_02/01/1952',
 'Date_02/01/1953',
 'Date_02/01/1954',
 'Date_02/02/1921',
 'Date_02/02/1922',
 'Date_02/02/1923',
 'Date_02/02/1924',
 'Date_02/02/1925',
 'Date_02/02/1926',
 'Date_02/02/1927',
 'Date_02/02/1928',
 'Date_02/02/1929',
 'Date_02/02/1930',
 'Date_02/02/1931',
 'Date_02/02/1932',
 'Date_02/02/1933',
 'Date_02/02/1934',
 'Date_02/02/1935',
 'Date_02/02/1936',
 'Date_02/02/1937',
 'Date_02/02/1938',
 'Date_02/02/1939',
 'Date_02/02/1940',
 'Date_02/02/1941',
 'Date_02/02/1942',
 'Date_02/02/1943',
 'Date_02/02/1944',
 'Date_02/02/1945',
 'Date_02/02/1946',
 'Date_02/02/1947',
 'Date_02/02/1948',
 'Date_02/02/1949',
 'Date_02/02/1950',
 'Date_02/02/1951',
 'Date_02/02/1952',
 'Date_02/02/1953',
 'Date_02/02/1954',
 'Date_02/03/1921',
 'Date_02/03/1922',
 'Date_02/03/1923',
 'Date_02/03/1924',
 'Date_02/03/1925',
 'Date_02/03/1926',
 'Date_02/03/1927',
 'Date_02/03/1928',
 'Date_02/03/1929',
 'Date_02/03/1930',
 'Date_02/03/1931',
 'Date_02/03/1932',
 'Date_02/03/1933',
 'Date_02/03/1934',
 'Date_02/03/1935',
 'Date_02/03/1936',
 'Date_02/03/1937',
 'Date_02/03/1938',
 'Date_02/03/1939',
 'Date_02/03/1940',
 'Date_02/03/1941',
 'Date_02/03/1942',
 'Date_02/03/1943',
 'Date_02/03/1944',
 'Date_02/03/1945',
 'Date_02/03/1946',
 'Date_02/03/1947',
 'Date_02/03/1948',
 'Date_02/03/1949',
 'Date_02/03/1950',
 'Date_02/03/1951',
 'Date_02/03/1952',
 'Date_02/03/1953',
 'Date_02/03/1954',
 'Date_02/04/1921',
 'Date_02/04/1922',
 'Date_02/04/1923',
 'Date_02/04/1924',
 'Date_02/04/1925',
 'Date_02/04/1926',
 'Date_02/04/1927',
 'Date_02/04/1928',
 'Date_02/04/1929',
 'Date_02/04/1930',
 'Date_02/04/1931',
 'Date_02/04/1932',
 'Date_02/04/1933',
 'Date_02/04/1934',
 'Date_02/04/1935',
 'Date_02/04/1936',
 'Date_02/04/1937',
 'Date_02/04/1938',
 'Date_02/04/1939',
 'Date_02/04/1940',
 'Date_02/04/1941',
 'Date_02/04/1942',
 'Date_02/04/1943',
 'Date_02/04/1944',
 'Date_02/04/1945',
 'Date_02/04/1946',
 'Date_02/04/1947',
 'Date_02/04/1948',
 'Date_02/04/1949',
 'Date_02/04/1950',
 'Date_02/04/1951',
 'Date_02/04/1952',
 'Date_02/04/1953',
 'Date_02/04/1954',
 'Date_02/05/1921',
 'Date_02/05/1922',
 'Date_02/05/1923',
 'Date_02/05/1924',
 'Date_02/05/1925',
 'Date_02/05/1926',
 'Date_02/05/1927',
 'Date_02/05/1928',
 'Date_02/05/1929',
 'Date_02/05/1930',
 'Date_02/05/1931',
 'Date_02/05/1932',
 'Date_02/05/1933',
 'Date_02/05/1934',
 'Date_02/05/1935',
 'Date_02/05/1936',
 'Date_02/05/1937',
 'Date_02/05/1938',
 'Date_02/05/1939',
 'Date_02/05/1940',
 'Date_02/05/1941',
 'Date_02/05/1942',
 'Date_02/05/1943',
 'Date_02/05/1944',
 'Date_02/05/1945',
 'Date_02/05/1946',
 'Date_02/05/1947',
 'Date_02/05/1948',
 'Date_02/05/1949',
 'Date_02/05/1950',
 'Date_02/05/1951',
 'Date_02/05/1952',
 'Date_02/05/1953',
 'Date_02/05/1954',
 'Date_02/06/1921',
 'Date_02/06/1922',
 'Date_02/06/1923',
 'Date_02/06/1924',
 'Date_02/06/1925',
 'Date_02/06/1926',
 'Date_02/06/1927',
 'Date_02/06/1928',
 'Date_02/06/1929',
 'Date_02/06/1930',
 'Date_02/06/1931',
 'Date_02/06/1932',
 'Date_02/06/1933',
 'Date_02/06/1934',
 'Date_02/06/1935',
 'Date_02/06/1936',
 'Date_02/06/1937',
 'Date_02/06/1938',
 'Date_02/06/1939',
 'Date_02/06/1940',
 'Date_02/06/1941',
 'Date_02/06/1942',
 'Date_02/06/1943',
 'Date_02/06/1944',
 'Date_02/06/1945',
 'Date_02/06/1946',
 'Date_02/06/1947',
 'Date_02/06/1948',
 'Date_02/06/1949',
 'Date_02/06/1950',
 'Date_02/06/1951',
 'Date_02/06/1952',
 'Date_02/06/1953',
 'Date_02/06/1954',
 'Date_02/07/1921',
 'Date_02/07/1922',
 'Date_02/07/1923',
 'Date_02/07/1924',
 'Date_02/07/1925',
 'Date_02/07/1926',
 'Date_02/07/1927',
 'Date_02/07/1928',
 'Date_02/07/1929',
 'Date_02/07/1930',
 'Date_02/07/1931',
 'Date_02/07/1932',
 'Date_02/07/1933',
 'Date_02/07/1934',
 'Date_02/07/1935',
 'Date_02/07/1936',
 'Date_02/07/1937',
 'Date_02/07/1938',
 'Date_02/07/1939',
 'Date_02/07/1940',
 'Date_02/07/1941',
 'Date_02/07/1942',
 'Date_02/07/1943',
 'Date_02/07/1944',
 'Date_02/07/1945',
 'Date_02/07/1946',
 'Date_02/07/1947',
 'Date_02/07/1948',
 'Date_02/07/1949',
 'Date_02/07/1950',
 'Date_02/07/1951',
 'Date_02/07/1952',
 'Date_02/07/1953',
 'Date_02/07/1954',
 'Date_02/08/1921',
 'Date_02/08/1922',
 'Date_02/08/1923',
 'Date_02/08/1924',
 'Date_02/08/1925',
 'Date_02/08/1926',
 'Date_02/08/1927',
 'Date_02/08/1928',
 'Date_02/08/1929',
 'Date_02/08/1930',
 'Date_02/08/1931',
 'Date_02/08/1932',
 'Date_02/08/1933',
 'Date_02/08/1934',
 'Date_02/08/1935',
 'Date_02/08/1936',
 'Date_02/08/1937',
 'Date_02/08/1938',
 'Date_02/08/1939',
 'Date_02/08/1940',
 'Date_02/08/1941',
 'Date_02/08/1942',
 'Date_02/08/1943',
 'Date_02/08/1944',
 'Date_02/08/1945',
 'Date_02/08/1946',
 'Date_02/08/1947',
 'Date_02/08/1948',
 'Date_02/08/1949',
 'Date_02/08/1950',
 'Date_02/08/1951',
 'Date_02/08/1952',
 'Date_02/08/1953',
 'Date_02/08/1954',
 'Date_02/09/1921',
 'Date_02/09/1922',
 'Date_02/09/1923',
 'Date_02/09/1924',
 'Date_02/09/1925',
 'Date_02/09/1926',
 'Date_02/09/1927',
 'Date_02/09/1928',
 'Date_02/09/1929',
 'Date_02/09/1930',
 'Date_02/09/1931',
 'Date_02/09/1932',
 'Date_02/09/1933',
 'Date_02/09/1934',
 'Date_02/09/1935',
 'Date_02/09/1936',
 'Date_02/09/1937',
 'Date_02/09/1938',
 'Date_02/09/1939',
 'Date_02/09/1940',
 'Date_02/09/1941',
 'Date_02/09/1942',
 'Date_02/09/1943',
 'Date_02/09/1944',
 'Date_02/09/1945',
 'Date_02/09/1946',
 'Date_02/09/1947',
 'Date_02/09/1948',
 'Date_02/09/1949',
 'Date_02/09/1950',
 'Date_02/09/1951',
 'Date_02/09/1952',
 'Date_02/09/1953',
 'Date_02/09/1954',
 'Date_02/10/1921',
 'Date_02/10/1922',
 'Date_02/10/1923',
 'Date_02/10/1924',
 'Date_02/10/1925',
 'Date_02/10/1926',
 'Date_02/10/1927',
 'Date_02/10/1928',
 'Date_02/10/1929',
 'Date_02/10/1930',
 'Date_02/10/1931',
 'Date_02/10/1932',
 'Date_02/10/1933',
 'Date_02/10/1934',
 'Date_02/10/1935',
 'Date_02/10/1936',
 'Date_02/10/1937',
 'Date_02/10/1938',
 'Date_02/10/1939',
 'Date_02/10/1940',
 'Date_02/10/1941',
 'Date_02/10/1942',
 'Date_02/10/1943',
 'Date_02/10/1944',
 'Date_02/10/1945',
 'Date_02/10/1946',
 'Date_02/10/1947',
 'Date_02/10/1948',
 'Date_02/10/1949',
 'Date_02/10/1950',
 'Date_02/10/1951',
 'Date_02/10/1952',
 'Date_02/10/1953',
 'Date_02/10/1954',
 'Date_02/11/1921',
 'Date_02/11/1922',
 'Date_02/11/1923',
 'Date_02/11/1924',
 'Date_02/11/1925',
 'Date_02/11/1926',
 'Date_02/11/1927',
 'Date_02/11/1928',
 'Date_02/11/1929',
 'Date_02/11/1930',
 'Date_02/11/1931',
 'Date_02/11/1932',
 'Date_02/11/1933',
 'Date_02/11/1934',
 'Date_02/11/1935',
 'Date_02/11/1936',
 'Date_02/11/1937',
 'Date_02/11/1938',
 'Date_02/11/1939',
 'Date_02/11/1940',
 'Date_02/11/1941',
 'Date_02/11/1942',
 'Date_02/11/1943',
 'Date_02/11/1944',
 'Date_02/11/1945',
 'Date_02/11/1946',
 'Date_02/11/1947',
 'Date_02/11/1948',
 'Date_02/11/1949',
 'Date_02/11/1950',
 'Date_02/11/1951',
 'Date_02/11/1952',
 'Date_02/11/1953',
 'Date_02/11/1954',
 'Date_02/12/1921',
 'Date_02/12/1922',
 'Date_02/12/1923',
 'Date_02/12/1924',
 'Date_02/12/1925',
 'Date_02/12/1926',
 'Date_02/12/1927',
 'Date_02/12/1928',
 'Date_02/12/1929',
 'Date_02/12/1930',
 'Date_02/12/1931',
 'Date_02/12/1932',
 'Date_02/12/1933',
 'Date_02/12/1934',
 'Date_02/12/1935',
 'Date_02/12/1936',
 'Date_02/12/1937',
 'Date_02/12/1938',
 'Date_02/12/1939',
 'Date_02/12/1940',
 'Date_02/12/1941',
 'Date_02/12/1942',
 'Date_02/12/1943',
 'Date_02/12/1944',
 'Date_02/12/1945',
 'Date_02/12/1946',
 'Date_02/12/1947',
 'Date_02/12/1948',
 'Date_02/12/1949',
 'Date_02/12/1950',
 'Date_02/12/1951',
 'Date_02/12/1952',
 'Date_02/12/1953',
 'Date_02/12/1954',
 'Date_03/01/1921',
 'Date_03/01/1922',
 'Date_03/01/1923',
 'Date_03/01/1924',
 'Date_03/01/1925',
 'Date_03/01/1926',
 'Date_03/01/1927',
 'Date_03/01/1928',
 'Date_03/01/1929',
 'Date_03/01/1930',
 'Date_03/01/1931',
 'Date_03/01/1932',
 'Date_03/01/1933',
 'Date_03/01/1934',
 'Date_03/01/1935',
 'Date_03/01/1936',
 'Date_03/01/1937',
 'Date_03/01/1938',
 'Date_03/01/1939',
 'Date_03/01/1940',
 'Date_03/01/1941',
 'Date_03/01/1942',
 'Date_03/01/1943',
 'Date_03/01/1944',
 'Date_03/01/1945',
 'Date_03/01/1946',
 'Date_03/01/1947',
 'Date_03/01/1948',
 'Date_03/01/1949',
 'Date_03/01/1950',
 'Date_03/01/1951',
 'Date_03/01/1952',
 'Date_03/01/1953',
 'Date_03/01/1954',
 'Date_03/02/1921',
 'Date_03/02/1922',
 'Date_03/02/1923',
 'Date_03/02/1924',
 'Date_03/02/1925',
 'Date_03/02/1926',
 'Date_03/02/1927',
 'Date_03/02/1928',
 'Date_03/02/1929',
 'Date_03/02/1930',
 'Date_03/02/1931',
 'Date_03/02/1932',
 'Date_03/02/1933',
 'Date_03/02/1934',
 'Date_03/02/1935',
 'Date_03/02/1936',
 'Date_03/02/1937',
 'Date_03/02/1938',
 'Date_03/02/1939',
 'Date_03/02/1940',
 'Date_03/02/1941',
 'Date_03/02/1942',
 'Date_03/02/1943',
 'Date_03/02/1944',
 'Date_03/02/1945',
 'Date_03/02/1946',
 'Date_03/02/1947',
 'Date_03/02/1948',
 'Date_03/02/1949',
 'Date_03/02/1950',
 'Date_03/02/1951',
 'Date_03/02/1952',
 'Date_03/02/1953',
 'Date_03/02/1954',
 'Date_03/03/1921',
 'Date_03/03/1922',
 'Date_03/03/1923',
 'Date_03/03/1924',
 'Date_03/03/1925',
 'Date_03/03/1926',
 'Date_03/03/1927',
 'Date_03/03/1928',
 'Date_03/03/1929',
 'Date_03/03/1930',
 'Date_03/03/1931',
 'Date_03/03/1932',
 'Date_03/03/1933',
 'Date_03/03/1934',
 'Date_03/03/1935',
 'Date_03/03/1936',
 'Date_03/03/1937',
 'Date_03/03/1938',
 'Date_03/03/1939',
 'Date_03/03/1940',
 'Date_03/03/1941',
 'Date_03/03/1942',
 'Date_03/03/1943',
 'Date_03/03/1944',
 'Date_03/03/1945',
 'Date_03/03/1946',
 'Date_03/03/1947',
 'Date_03/03/1948',
 'Date_03/03/1949',
 'Date_03/03/1950',
 'Date_03/03/1951',
 'Date_03/03/1952',
 'Date_03/03/1953',
 'Date_03/03/1954',
 'Date_03/04/1921',
 'Date_03/04/1922',
 'Date_03/04/1923',
 'Date_03/04/1924',
 'Date_03/04/1925',
 'Date_03/04/1926',
 'Date_03/04/1927',
 'Date_03/04/1928',
 'Date_03/04/1929',
 'Date_03/04/1930',
 'Date_03/04/1931',
 'Date_03/04/1932',
 'Date_03/04/1933',
 'Date_03/04/1934',
 'Date_03/04/1935',
 'Date_03/04/1936',
 'Date_03/04/1937',
 'Date_03/04/1938',
 'Date_03/04/1939',
 'Date_03/04/1940',
 'Date_03/04/1941',
 'Date_03/04/1942',
 'Date_03/04/1943',
 'Date_03/04/1944',
 'Date_03/04/1945',
 'Date_03/04/1946',
 'Date_03/04/1947',
 'Date_03/04/1948',
 'Date_03/04/1949',
 'Date_03/04/1950',
 'Date_03/04/1951',
 'Date_03/04/1952',
 'Date_03/04/1953',
 'Date_03/04/1954',
 'Date_03/05/1921',
 'Date_03/05/1922',
 'Date_03/05/1923',
 'Date_03/05/1924',
 'Date_03/05/1925',
 'Date_03/05/1926',
 'Date_03/05/1927',
 'Date_03/05/1928',
 'Date_03/05/1929',
 'Date_03/05/1930',
 'Date_03/05/1931',
 'Date_03/05/1932',
 'Date_03/05/1933',
 'Date_03/05/1934',
 'Date_03/05/1935',
 'Date_03/05/1936',
 'Date_03/05/1937',
 'Date_03/05/1938',
 'Date_03/05/1939',
 'Date_03/05/1940',
 'Date_03/05/1941',
 'Date_03/05/1942',
 'Date_03/05/1943',
 'Date_03/05/1944',
 'Date_03/05/1945',
 'Date_03/05/1946',
 'Date_03/05/1947',
 'Date_03/05/1948',
 'Date_03/05/1949',
 'Date_03/05/1950',
 'Date_03/05/1951',
 'Date_03/05/1952',
 'Date_03/05/1953',
 'Date_03/05/1954',
 'Date_03/06/1921',
 'Date_03/06/1922',
 ...]

In [9]:
# baseline predictions are on the sunspot averages
baseline_preds = test_merged_data[:, feature_list.index('sunspot average')]

# baseline errors, and display average baseline error
baseline_errors = abs(baseline_preds - test_labels)

print('Average baseline error: ', round(np.mean(baseline_errors), 2))

Average baseline error:  56.84

In [ ]:
# import Random forest
from sklearn.ensemble import RandomForestRegressor

# instantiate with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

# train model on training data
rf.fit(train_merged_data, train_labels);

In [ ]:
# forest's predict method on the test data
predictions = rf.predict(merged_data)

# calculate absolute errors
errors = abs(predictions - test_labels)

# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors),2), 'degrees.')

In [ ]:
# mean absolute percentage error (mape)
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy: ', round(accuracy, 2), '%.')

In [ ]:
# Visualisation
from sklearn.tree import export_graphviz
import pydot

# pull out one tree from forest
tree = rf.estimators_[5]

# Visualisation
from sklearn.tree import export_graphviz
import pydot

# pull out one tree from forest
tree = rf.estimators_[5]

# Export to a dot file

export_graphviz(tree, out_file = 'tree.dot', feature_names = merged_data_list, rounded = True, precision = 1)

# use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')

# write graph to png file
graph.write_png('tree.png')

In [ ]:
# limit depth to 3 levels
rf_small = RandomForestRegressor(n_estimators = 10, max_depth = 3)
rf_small.fit(train_features, train_labels)

# extract small tree
tree_small = rf_small_estimators_[5]

# Export to a dot file

export_graphviz(small_tree, out_file = 'small_tree.dot', feature_names = merged_data_list, rounded = True, precision = 1)

# use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('small_tree.dot')

# write graph to png file
graph.write_png('small_tree.png')

In [ ]:
# numerical features of importances
importances = list(rf.feature_importances)

# list of tuples with variable and importance
features_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]

# sort feature importances
feature_importances = sorted(feature_importances, key = lambda x : x[1], reverse=True)

# print out feature and importance
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

In [ ]:
# New random forest with only the two most important variables
rf_most_important = RandomForestRegressor(n_estimators= 1000, random_state=42)

# Extract the two most important features
important_indices = [feature_list.index('Max at 9h (F)'), feature_list.index('Min at 9h (F)')]
train_important = train_features[:, important_indices]

test_important = test_features[:, important_indices]# Train the random forest
rf_most_important.fit(train_important, train_labels)# Make predictions and determine the error

# Display the performance metrics
predictions = rf_most_important.predict(test_important)errors = abs(predictions - test_labels)


print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')mape = np.mean(100 * (errors / test_labels))
accuracy = 100 - mapeprint('Accuracy:', round(accuracy, 2), '%.')

In [ ]:
# Import matplotlib for plotting and use magic command for Jupyter Notebooks
import matplotlib.pyplot as plt%matplotlib inline

# Set the style
plt.style.use('fivethirtyeight')

# list of x locations for plotting
x_values = list(range(len(importances)))

# Make a bar chart
plt.bar(x_values, importances, orientation = 'vertical')

# Tick labels for x axis
plt.xticks(x_values, feature_list, rotation='vertical')

# Axis labels and title
plt.ylabel('Importance'); plt.xlabel('Variable'); plt.title('Variable Importances');

In [ ]:
# Use datetime for creating date objects for plotting
import datetime

# Dates of training values
months = features[:, feature_list.index('month')]
days = features[:, feature_list.index('Daily')]
years = features[:, feature_list.index('year')]

# list and convert to datetime objects
dates = [str(int(year)) + '-' + str(int(month)) + '-' + str(int(day)) for year, month, day in zip(years, months, days)]
dates = [datetime.datetime.strptime(date, '%Y-%m-%d') for date in dates]

# true dates and values
true_data = pd.DataFrame(data = {'date':dates, 'sunspot average':labels})

# Dates of predictions

months = test_merged_data[:, feature_list.index('month')]
days = test_merged_data[:, feature_list.index('daily')]
years = test_merged_data[:, feature_list.index('year')]

test_dates = [str(int(year)) + '-' + str(int(month)) + '-' + str(int(day)) for year, month, day in zip(years, months, days)]
test_dates = [datetime.datetime.strptime(date, '%Y-%m-%d') for date in dates]

# predictions dataframe
predictions_data = pd.DataFrame(data = {'data': test_dates, 'predictions':predictions})

# plot actuals
plt.plot(predictions_data['date'], predictions_data['prediction'], 'ro', label = 'prediction')
plt.xticks(rotation= '60');
plt.legend()

# Graph labels
plt.xlabel('Date');
plt.ylabel('Max Temp');
plt.title('Actual and Predicted Values');

In [ ]:
# make accessible for plotting
true_data['Max at 21h (C)'] = merged_data[:, feature_list.index('Max at 21h (C)')]
true_data['average sunspots'] = merged_data[:, feature_list.index('average sunspots')]
true_data['Min at 21h (C)'] = merged_data[:, feature_list.index('Min at 21h (C)')]

# plot all the data as line
plt.plot(true_data['date'], true_data['average sunspots'], 'b-', label = 'average sunspots', alpha = 1.0)
plt.plot(true_data['date'], true_data['Max at 21h (C)'], 'y-', label = 'Max at 21h (C)', alpha = 1.0)
plt.plot(true_data['date'], true_data['Min at 21h (C)'], 'k-', label = 'Min at 21h (C)', alpha = 1.0)

plt.legend();
plt.xticks(rotation = '60');

plt.xlabel('Date');
plt.ylabel('Maximum Temp');
plt.title('Actual');

In [ ]:
##############################################################################################~

In [ ]:
## Naive Bayes 
df = pd.read_csv('/home/damien/Desktop/Data_Group_Project/SN_m_tot_V2.0EDIT.csv')
df2 = pd.read_csv('/home/damien/Desktop/Data_Group_Project/Birr Castle telegraphic reporting station_1921-1956.csv')

naive = df.merge(df2, left_on=['year','month'], right_on=['Year','Month'])
X, y, col_names = naive['sunspot average'], naive['Max at 21 (C)'], feature_list
X = pd.DataFrame(X, cols = col_names)

X_train, X_val, y_train, y_val = train_test_split(X,y, random_state = 44)

In [ ]:
# this is fitting the data, and statistics for the training set
means = X_train.groupby(y_train).apply(np.mean)
stds = X_train.groupby(y_train).apply(lambda x: len(x)) / X_train.shape[0]

In [ ]:
y_preds = []

for elem in range(X_val.shape[0]):
    p = {}
    
    for c1 in np.unique(y_train):
        
        p[c1] = prob.iloc[c1]
        
        for index, param in enumerate(X_val.iloc[elem]):
            
            p[c1] *= norm.pdf(param, means.iloc[c1, index])
    y_pred.append(pd.Series(p).values.argmax())

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

accuracy_score(y_val, model.predict(X_val))